version: '3.8'

services:
  node:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: jemandandere-node-dev
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: jemandandere-nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 